### ISSUE TITLE
the function of searching doesn't work in PageAndListRowFragment

### ISSUE THREAD

**Issue by tracyliu1** [googlesamples/leanback-showcase#18]
![image](https://cloud.githubusercontent.com/assets/17140629/22148028/c6226332-df46-11e6-8d00-08a82c69eb0f.png)
It is no response when I click the search button in PageAndListRowFragment,but it is do well in other fragment .Even they both extends BrowseFragment. Do you understand my words?

**Comment by Mokto** [comment]
I confirm this does not work for me neither.

It seems to be when we use BrowseFragment.FragmentFactory.

Thanks !

**Comment by dakegu** [comment]
It's because CustomTitleView.TitleViewAdapter forgot to implement setOnSearchClickedListener()

**Comment by dakegu** [comment]
Updated sample code, it should work now

**Comment by Mokto** [comment]
Thanks !!
