### ISSUE TITLE
Headers Fragment

### ISSUE THREAD

**Issue by viktordolgalyov** [googlesamples/leanback-showcase#21]
Is Leanback has default possibility to make HeadersFragment non scrollable like it implemented in the Google Play Store?

**Comment by dakegu** [comment]
It does not make sense if you have more items than the screen can show, but you can change VerticalGridView's alignment settings:

setWindowAlignment(ALIGN_BOTH_EDGE)
setPadding(getPaddingLeft(), 400, getPaddingRight(), 400)
