### ISSUE TITLE
ItemViewClickedListener not working first 3 items

### ISSUE THREAD

**Issue by Karthikg206** [googlesamples/leanback-showcase#22]
I am using this MusicPlayer sample app. In My AlbumDetailsFragment extends Details Fragment i registered 
"ItemViewSelectedListener" and "ItemViewClickedListener". Here  ItemViewSelectedListener works all items but **ItemViewClickedListener** not working first three items remaining working fine.

How to fix?

**Comment by dakegu** [comment]
It will be fixed in next release,  to workaround, call verticalGridView.getLayoutManager().setItemPrefetchEnabled(false)

**Comment by Karthikg206** [comment]
@dakegu In which place i will use verticalGridView.getLayoutManager().setItemPrefetchEnabled(false),My DetailsFragment????

But i'm not using verticalGridView.How i will get from DetailsFragment????

**Comment by dakegu** [comment]
in onStart():
getRowsFragment().getVerticalGridView().getLayoutManager().setItemPrefetchEnabled(false)

**Comment by MizzleDK** [comment]
`getVerticalGridView()` is not public.

**Comment by dakegu** [comment]
should be fixed in 26.0.0 alpha 1, the workaround no longer needed.
