### ISSUE TITLE
Unable to run the sample app on any device

### ISSUE THREAD

**Issue by khat33b** [googlesamples/leanback-showcase#32]
I am getting `minSdk(API 25, O preview) != deviceSdk(API 23)` error when running the app on every device with the `deviceSdk` being the Android OS version. I have not changed anything in the sample app.

Please fix it or tell me how to fix it.

**Comment by tracyliu1** [comment]
I don`t know why the SDK version must be 26? It`s difficult for deveplor to build the corret Enviroment

**Comment by tracyliu1** [comment]
for Exmaple : 26.0.0-rc2 buildVersiontools  is not Avaliable. The SDK manager say that

**Comment by zaclimon** [comment]
I got it working by downloading the API 26 SDK (Android O) and then changing the CompileSDKVersion, build tools and the TargetSDKVersion to 26 (Since the SDK is now in final release instead of the RC ones)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
