### ISSUE TITLE
Cannot click first item of recommend in DetailViewExampleFragment

### ISSUE THREAD

**Issue by ToaiLC** [googlesamples/leanback-showcase#33]
I checkout code and run, In the DetailViewExampleFragment, I replace some code as below:
```
@Override
    public void onItemClicked(Presenter.ViewHolder itemViewHolder, Object item,
                              RowPresenter.ViewHolder rowViewHolder, Row row) {
//        if (!(item instanceof Action)) return;
//        Action action = (Action) item;
//
//        if (action.getId() == ACTION_RELATED) {
//            setSelectedPosition(1);
//        } else {
//            Toast.makeText(getActivity(), getString(R.string.action_cicked), Toast.LENGTH_LONG)
//                    .show();
//        }
        Log.d("onItemClicked", item.toString());
    }
```
But When I click first item in  relate or recommend row log is not be shown.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
