### ISSUE TITLE
Can't refresh the data in PageAndListRowFragment

### ISSUE THREAD

**Issue by Pumayk26** [googlesamples/leanback-showcase#36]
I'm using this to add multiple rows for each header item. now I'm unable to refresh data in this fragment. I'll provide an example how I set data and how I tried to refresh the data.
this is my onCreate

`public void onCreate(Bundle savedInstanceState) {`
        `super.onCreate(savedInstanceState);`
 ` setupUi();`
`  loadData();`
 ` mBackgroundManager = BackgroundManager.getInstance(getActivity());`
`  mBackgroundManager.attach(getActivity().getWindow());`
 ` getMainFragmentRegistry().registerFragment(PageRow.class,new PageRowFragmentFactory(mBackgroundManager,myObject));`
`}`

I've passed myObject into PageRowFragmentFactory, That's how i pass data into my fragments.
When I refresh the data (i do the same thing in onCreate with different data) 
` getMainFragmentRegistry().registerFragment(PageRow.class,new PageRowFragmentFactory(mBackgroundManager,myObject));`

data never refreshed, and the important thing is `createFragment()` method in PageRowFragmentFactory is not calling. What could be the issue?

**Comment by Allan-Nava** [comment]
Hi,

is possibile add a progressbar on change the pagelistrow?

Thanks

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
