### ISSUE TITLE
Video Grid Examples Causing illegalStateException

### ISSUE THREAD

**Issue by runouttime** [googlesamples/leanback-showcase#46]
Line 121 of  VideoGridExampleFragment.java

`VideoRow[] videoRows = new Gson().fromJson(videoRowsJson, VideoRow[].class);`

Causes a Fatal Exception

> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 246 path $[0].videos[0].sources

**Comment by runouttime** [comment]
Turns out VideoCard.java is expecting a string for sources but in the json file 

> https://storage.googleapis.com/android-tv/android_tv_videos_new.json

it is an array, the json file needs to be changed or you change VideoCard class to be as follows to accept an array
```
public class VideoCard extends Card {

    @SerializedName("sources") private String[] mVideoSource = new String[0];
    @SerializedName("background") private String mBackgroundUrl = "";
    @SerializedName("studio") private String mStudio = "";

    public VideoCard() {
        super();
        setType(Type.VIDEO_GRID);
    }

    public String getVideoSource() {
        return  mVideoSource[0];
    }

    public void setVideoSource(String sources) {
        mVideoSource[0] = sources;
    }

    public String getBackground() {
        return mBackgroundUrl;
    }

    public void setBackground(String background) {
        mBackgroundUrl = background;
    }

    public String getStudio() {
        return mStudio;
    }

    public void setStudio(String studio) {
        mStudio = studio;
    }
}
```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
