### ISSUE TITLE
How to add a background in the PlaybackActivity?

### ISSUE THREAD

**Issue by androidwqn** [googlesamples/leanback-showcase#47]
I see the example picture, music example has a background picture, how to add a background picture in the PlaybackActivity?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
