### ISSUE TITLE
How to set OnItemViewSelectedListener for header

### ISSUE THREAD

**Issue by MolchanovDmitry** [googlesamples/leanback-showcase#51]
Good day.

How can I set onItemViewClickedListener event for header items?
I tried with code below
getHeadersFragment().setOnHeaderViewSelectedListener((viewHolder, row) -> Utils.print("test"));
but get null in onCreate/onAttach, and application freezes in onActivityCreated.

Thanks you.

**Comment by morkovkin** [comment]
i think yor problem happen becouse headers fragment created in method onCreateView. Its mean you must first call siper.onCreateView. After you can use getHeadersFragment

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
