### ISSUE TITLE
Expresso testing

### ISSUE THREAD

**Issue by morkovkin** [googlesamples/leanback-showcase#52]
Hello there! I can't found information about ui testing for Android TV. I know possible use unit testing to test functional... But how to use espresso or seam framework to testing ui?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
