### ISSUE TITLE
Custom Fragment focus

### ISSUE THREAD

**Issue by morkovkin** [googlesamples/leanback-showcase#53]
Hello!I have focus problem witn my  i have layout like this

```
<FrameLayout>
    <CustomViewOne android:id="@+id/vOne"></FrameLayout>
    <CustomViewTwo android:id="@+id/vTwo"></FrameLayout>
</FrameLayout>
```

My CustomViewOne its class  extends FrameLayout and have one button in layout. CustomViewTwo seem class have one button too. When i use vOne.setVisibility(View.GONE) i see my vTwo. When i press button down in my keyboard my vTwo lost focus, and button from vOne can found focus... Actualy i can click on invisible view. How to fix this problem?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
