### ISSUE TITLE
The Leanback SearchOrbView is not looking right when it has focus

### ISSUE THREAD

**Issue by aglt** [googlesamples/leanback-showcase#55]
It has a square shadow on focus when I created a custom title bar. To demonstrate I created a demo project on github:

https://github.com/aglt/SearchOrbBug

**Comment by yzheka** [comment]
Just add some padding to SearchOrbView

**Comment by aglt** [comment]
@yzheka the problem is not that the orb it self is being clipped off, the problem is that the drop shadow is square when the orb has focus. So changing the padding does not solve anything.
![image](https://user-images.githubusercontent.com/4155016/39124365-b8f96450-46ea-11e8-92d9-9c4c8b6ce7ca.png)

**Comment by yzheka** [comment]
I've added 16dp padding and it is solved problem for me (I also set clipToPadding=false and clipChildern=false)

**Comment by aglt** [comment]
Yes, clipChildren="false" and clipToPadding="false" is what I was missing.. This solves the issue! Thanks! 

```
    <android.support.v17.leanback.widget.SearchOrbView
        android:id="@+id/search_orb_view"
        android:layout_height="wrap_content"
        android:layout_width="wrap_content"
        android:transitionGroup="true"
        android:layout_gravity="center_vertical|start"
        android:layout_marginTop="8dp"
        android:clipChildren="false"
        android:clipToPadding="false"
        android:padding="16dp" />
```
