### ISSUE TITLE
PageAndListRowFragment SettingsFragment - multirows for one header 

### ISSUE THREAD

**Issue by AlekseyKonovalov** [googlesamples/leanback-showcase#57]
the scroll doesn’t follow the current focused item inside a SettingsFragment  (if there are more than 3 rows)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
