### ISSUE TITLE
Search fragment closing after gaining focus on results

### ISSUE THREAD

**Issue by PrPetkov** [googlesamples/leanback-showcase#58]
In the search fragment when we have committed a search with the keyboard and we have search results the fragment is closing when the search query is submitted with the back button. We can see that on action down of the back button the results are gaining focus and the keyboard is hiding(as expected) but on action up the screen is closing.
I believe this is a bug in the leanback framework since this is reproducing in this showcase. Is there a workaround to disable the closing of the screen.

**Comment by Ryder68** [comment]
I am also experiencing the same problem as you.
Did you find a solution?

**Comment by PrPetkov** [comment]
I have found a hacky solution, I hope that the leanback team will fix this bug, until then I will use this - https://stackoverflow.com/questions/50268110/leanback-search-fragment-closing-after-gaining-focus-on-results/50714365#50714365

**Comment by DWinnicki** [comment]
I am also experiencing the same issue.
With no results on screen, the back button closes the keyboard correctly.
When search results are displayed, pressing the back button closes the keyboard, focuses on the first result and finishes the activity.
The only way to navigate the results is to click the SEARCH on the keyboard.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
