### ISSUE TITLE
Fast-forward, Rewind and Video Scrubbing Don't Work on Android OS 6

### ISSUE THREAD

**Issue by bkadirbeyoglu** [googlesamples/leanback-showcase#59]
I am getting reports that the fast-forward, rewind and video scrubbing features don't work on an Android 6 device, namely Xiaomi MiBox3. The app just hangs. They are working fine on my Google Nexus Player running on Android OS 8. What could be the reason? Thanks in advance.

Here's the code I am using in VideoMediaPlayerGlue.java:

```
/** Skips backwards 10 seconds. */
    public void rewind() {
        Crashlytics.log("rewind action");
        long newPosition = getCurrentPosition() - TEN_SECONDS;
        newPosition = (newPosition < 0) ? 0 : newPosition;
        getPlayerAdapter().seekTo(newPosition);
    }

    /** Skips forward 10 seconds. */
    public void fastForward() {
        Crashlytics.log("fast-forward action");
        if (getDuration() > -1) {
            long newPosition = getCurrentPosition() + TEN_SECONDS;
            newPosition = (newPosition > getDuration()) ? getDuration() : newPosition;
            getPlayerAdapter().seekTo(newPosition);
        }
    }
```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
