### ISSUE TITLE
Multiple build issues

### ISSUE THREAD

**Issue by ninovanhooff** [googlesamples/leanback-showcase#60]
Manifest merger failed: changing buildTools and supportlib to 26.1.0 in build.gradle fixes this

The gradle version is not compatible with the latest Android Studio

In `VideosViewModel`, import `import android.arch.core.util.Function;` could not be resolved

**Comment by S0und** [comment]
> import android.arch.core.util.Function; could not be resolved

https://stackoverflow.com/questions/46405863/cannot-access-class-android-arch-core-util-function

> downgrading support library from 26.1.0 to 26.0.2 and it started working

The moment i do the downgrading, i got this: 


> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:design:26.0.2] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:support-core-utils:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**UPDATE:**

I got it working with Android Studio 3.0 (https://developer.android.com/studio/archive), just download the zipped version.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
