### ISSUE TITLE
Wrong Aspect Ratio

### ISSUE THREAD

**Issue by enigmadevs** [googlesamples/leanback-showcase#61]
I implemented VideoExampleWithExoPlayerActivity in my app. All works fine except aspect ratio in some videos. It happens with videos with very wide aspect ratio (21:9, for example). Instead shows horizontal black stripes in the top and the bottom of the video, it stretech the video to have same height that screen.

In your sample video it's 16:9 and it doesn't happen, what can i do to show video with its real aspect ratio?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
