### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by xayo69** [googlesamples/leanback-showcase#64]
项目导入studio后跑不起来

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
