### ISSUE TITLE
udp audio can't paly in Exoplayer adapter

### ISSUE THREAD

**Issue by MuthuKrishnanO** [googlesamples/leanback-showcase#65]
10-08 20:55:46.015 1465-4317/? E/OMXNodeInstance: getExtensionIndex(6f:hisi.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
10-08 20:55:46.015 13897-13990/com.example.android.persistence E/ACodec: [OMX.hisi.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
10-08 20:55:46.016 13897-13990/com.example.android.persistence I/ACodec: [OMX.hisi.video.decoder.avc] prepareForAdaptivePlayback(528x576)
10-08 20:55:46.020 1465-13991/? D/HISI_OMXVDEC: [OmxState] Loaded --> Idle_Pending
10-08 20:55:46.020 13897-13990/com.example.android.persistence I/ACodec: [OMX.hisi.video.decoder.avc] Allocating 4 buffers of size 2097152 on input port
10-08 20:55:46.021 1465-1138/? D/HISI_OMXVDEC: Alloc buffer  vir:0x0x0 phy:0x1adc000, size:2097152 dir:0 sec:0 success!
10-08 20:55:46.022 1465-24889/? D/HISI_OMXVDEC: Alloc buffer  vir:0x0x0 phy:0x1cdd000, size:2097152 dir:0 sec:0 success!
10-08 20:55:46.023 1465-31203/? D/HISI_OMXVDEC: Alloc buffer  vir:0x0x0 phy:0x1ede000, size:2097152 dir:0 sec:0 success!
10-08 20:55:46.024 1465-4318/? D/HISI_OMXVDEC: Alloc buffer  vir:0x0x0 phy:0x20df000, size:2097152 dir:0 sec:0 success!
10-08 20:55:46.025 13897-13990/com.example.android.persistence I/ACodec: [OMX.hisi.video.decoder.avc] will output to SurfaceView
10-08 20:55:46.025 13897-13990/com.example.android.persistence I/ACodec: Output will queue to overlay.
10-08 20:55:46.025 1465-31203/? D/HISI_OMXVDEC: get vpss bypass info = 0 (w = 528,h = 576)
10-08 20:55:46.025 13897-13990/com.example.android.persistence I/ACodec:  isVideoBypass -- omxBypass = 0, queuesToNativeWindow = 1
10-08 20:55:46.025 1465-4318/? D/HISI_OMXVDEC: set vpss bypass info = 0
10-08 20:55:46.026 13897-13990/com.example.android.persistence I/ACodec: [OMX.hisi.video.decoder.avc] Allocating 7 buffers from a native window of size 456192 on output port

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
