### ISSUE TITLE
Unable to build project in android studio

### ISSUE THREAD

**Issue by vijaykolapalli** [googlesamples/leanback-showcase#66]
When importing project I'm getting a lot of errors.(room db , error: package android.arch.core.util does not exist)

**Comment by MNGsulochana** [comment]
I am also facing same issue .I am using studio 3.2.1 ,I am unable to build project its showing lot of gradle and third party dependencies

**Comment by coofeeing** [comment]
I am also。。。

**Comment by S0und** [comment]
Use Android Studio 3.0: https://developer.android.com/studio/archive

**Comment by rocappdev** [comment]
same issue

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
