### ISSUE TITLE
AndroidX migration issue

### ISSUE THREAD

**Issue by Veeresh8** [googlesamples/leanback-showcase#68]
We just moved to **AndroidX** and we are using RowsSupportFragment, ArrayObjectAdapter to populate our list. Now, the problem here is that the scroll is broken, where the first item is snapped to the top always. However, when we use **android.support.v17.leanback** the scroll is fine.

Is this a known issue? Any workarounds for this?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
