### ISSUE TITLE
fragment design through xml

### ISSUE THREAD

**Issue by supriyatambe131995** [googlesamples/leanback-showcase#71]
How we can add custom design for fragment through xml file example if we want to used custom layout where web view given now

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
