### ISSUE TITLE
Loader issue

### ISSUE THREAD

**Issue by supriyatambe131995** [googlesamples/leanback-showcase#72]
loader is showing when i load webview at pagefragment inside custom fragment activity and i unable to find why the loader is loading.. becuase i have comment all json call inside page_rowlistfragment

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
