### ISSUE TITLE
Search icon hide inside custom fragement 

### ISSUE THREAD

**Issue by supriyatambe131995** [googlesamples/leanback-showcase#73]
Hi ,

Webview fragment which is custom fragement search icon hide inside that i want to show search icon on that page too.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
