### ISSUE TITLE
Exoplayer button handling 

### ISSUE THREAD

**Issue by srinivasgoud** [googlesamples/leanback-showcase#74]
Hi,

Can you please guide me to handle event of remote Button of TV in ExoPlayerAdapter.

best Regards,
srinivas

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
