### ISSUE TITLE
Slowing the scroll speed of browseFragment

### ISSUE THREAD

**Issue by vipulyaara** [googlesamples/leanback-showcase#80]
[Question]
I am using BrowseSupportFragment and want to slow down the speed of recyclerView when a navigation key is long pressed. I have tried everything I could. 

There are multiple queries on StackOverflow but none of them is answered. I think it would be a great help to me and some other people if you can explain how to do this.

**Comment by andreyriz** [comment]
Same problem, if youre decided this problem write me on mail andreyriz2909@gmail.com

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
