### ISSUE TITLE
Instead of creating Fragment every time on menu click how it's possible to check by findFragmentByTag()?

### ISSUE THREAD

**Issue by iskuhis** [googlesamples/leanback-showcase#81]
```private class PageRowFragmentFactory : BrowseSupportFragment.FragmentFactory<Fragment>() {
  override fun createFragment(row: Any): Fragment {
    row as PageRow
    return PageFragment.newInstance(menuItem = row.menuItem)
  }
}```

I have just changed it to Kotlin,
and every time clicking menu item ,creates new instance of Fragment (edited) 
my question how is it possible instead of creating check
by supportFragmentManager.findFragmentByTag()
and if it null then create ?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
