### ISSUE TITLE
How to use PlaybackSeekDataProvider and take snapshots from running video?

### ISSUE THREAD

**Issue by droid-wise** [googlesamples/leanback-showcase#82]
This is probably a stupid question, but how should I use the example in real case. With the following example using this two files: `PlaybackSeekAsyncDataProvider` and `PlaybackSeekDiskDataProvider`, I'm getting yellow cards with text inside when scrubbing video. So how can I make there snapshots from real video. I would really appreciate if someone helps me with this. I'm pretty new with Android TV.

**Comment by SalehDehqanpour** [comment]
I also wish to know is there a way in leanback to extract thumbnails from streaming video?!

**Comment by langaliamayank** [comment]
> This is probably a stupid question, but how should I use the example in real case. With the following example using this two files: `PlaybackSeekAsyncDataProvider` and `PlaybackSeekDiskDataProvider`, I'm getting yellow cards with text inside when scrubbing video. So how can I make there snapshots from real video. I would really appreciate if someone helps me with this. I'm pretty new with Android TV.

  MediaMetadataRetriever retriever = new MediaMetadataRetriever();
            if (Build.VERSION.SDK_INT >= 14)
                retriever.setDataSource(streamUrl, new HashMap<String, String>());
            else
                retriever.setDataSource(streamUrl);

            long pos = getSeekPositions()[index];
            Log.d("SeekProvider", "position: " + pos);
            Bitmap bmp = retriever.getFrameAtTime(pos,
                    MediaMetadataRetriever.OPTION_CLOSEST);
            retriever.release();

Instead of 

//            Bitmap bmp1 = Bitmap.createBitmap(500, 281, Bitmap.Config.ARGB_8888);
//            Canvas canvas = new Canvas(bmp1);
//            canvas.drawBitmap(bmp, 500, 281, null);
//            canvas.drawColor(Color.WHITE);
//            canvas.drawText(path, 10, 80, mPaint);
//            canvas.drawText(Integer.toString(index), 10, 150, mPaint);

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
