### ISSUE TITLE
Leanback Library & Paging Library

### ISSUE THREAD

**Issue by wusadurski** [googlesamples/leanback-showcase#83]
Has anyone had any success using Architecture Components Paging Library for paging in Leanback? Specifically I'm interested in paging in VerticalGridSupportFragment. We managed to extend ObjectAdapter to work together with PagedList.Callback and it works well but does not support updating list contents using AsyncPagedListDiffer due to too many classes and fields being private or package-private. I'm wondering if anyone succeeded with making Leanback and Paging Library work together without forking any of the two.

**Comment by geekman7473** [comment]
This is a current item of interest for my team as well. Any input from the maintainers would be appreciated.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
