### ISSUE TITLE
Service loop error

### ISSUE THREAD

**Issue by droidyayu** [googlesamples/leanback-showcase#84]
E/DiscoveryService: SsdpNanoHTTPD - Error in Service loop - null;
Continuously getting this error when trying to run Video consumption examples with exo player.

**Comment by droidyayu** [comment]
Player is giving drm exception

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
