### ISSUE TITLE
Did you forget to include architecture components with leanback examples?

### ISSUE THREAD

**Issue by xbit** [googlesamples/leanback-showcase#85]
Hello,
It seems that [ArchitectureComponentsWithLeanback](https://github.com/googlesamples/leanback-showcase/blob/master/ArchitectureComponentsWithLeanback.md) readme was created two years go and there are still no examples on whether it is possible to use them with existing leanback components. 

The current examples don't use Room database and rely on Cursor. 

Can someone provide an update on this?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
